backend:
  name: git-gateway
  branch: cms
media_folder: "src/projects/assets"
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Short Description"
        name: "description"
        widget: "string"
      - label: "Long Description"
        name: "body"
        widget: "markdown"
